(function () {
  async function saveSearchCount() {
    const current = await inkleaf.host.kv.get({ key: "searchCount" });
    const next = Number(current || 0) + 1;
    await inkleaf.host.kv.set({ key: "searchCount", value: next });
    return next;
  }

  inkleaf.register({
    describe: async function () {
      return {
        schemaVersion: 1,
        actions: [{ id: "host-smoke", title: "Host API smoke test" }],
        settings: []
      };
    },

    search: async function (request) {
      const count = await saveSearchCount();
      await inkleaf.host.log("info", "fixture search", { query: String(request.query || ""), count: String(count) });
      return {
        items: [{
          sourceId: "fixture-comic",
          title: "Fixture Comic",
          subtitle: "Search query: " + String(request.query || ""),
          tags: ["fixture"],
          opaqueContext: { fixture: true }
        }],
        nextCursor: null
      };
    },

    detail: async function () {
      return {
        sourceId: "fixture-comic",
        title: "Fixture Comic",
        subtitle: "Runtime verification source",
        description: "This record is generated by the checked-in fixture plugin.",
        opaqueContext: { fixture: true, detail: true }
      };
    },

    chapters: async function () {
      return {
        sourceId: "fixture-comic",
        revision: "fixture-r1",
        chapters: [
          { chapterId: "chapter-1", title: "Chapter 1", number: 1, revision: "chapter-1-r1", opaqueContext: { fixture: true } },
          { chapterId: "chapter-2", title: "Chapter 2", number: 2, revision: "chapter-2-r1", opaqueContext: { fixture: true } }
        ]
      };
    },

    pages: async function (request) {
      return {
        sourceId: "fixture-comic",
        chapterId: String(request.chapterId || "chapter-1"),
        revision: String(request.revision || "fixture-r1"),
        pages: [
          { pageId: "page-1", index: 0, url: "https://example.com/fixture/page-1.jpg" },
          { pageId: "page-2", index: 1, url: "https://example.com/fixture/page-2.jpg" }
        ]
      };
    },

    invokeAction: async function (request, context) {
      if (request.actionId !== "host-smoke") throw new Error("Unknown fixture action");
      const signal = context && context.signal;
      const now = await inkleaf.host.clock.now(signal);
      await inkleaf.host.kv.set({ key: "lastSmoke", value: now.epochMs }, signal);
      await inkleaf.host.cookie.set({
        url: "https://example.com/",
        setCookie: "inkleaf_fixture=1; Path=/"
      }, signal);
      const response = await inkleaf.host.http.request({
        method: "GET",
        url: "https://example.com/"
      }, signal);
      if (response.bodyHandle) await inkleaf.host.http.close({ handle: response.bodyHandle }, signal);
      await inkleaf.host.log("info", "fixture host smoke complete", { status: String(response.statusCode) }, signal);
      return {
        statusCode: response.statusCode,
        cookieCount: (await inkleaf.host.cookie.list(signal)).length,
        epochMs: now.epochMs
      };
    }
  });
})();
