organization:
  id: 2a3af562-8226-4cab-9a58-6b9248ccd8e8
  name: AEXDC
project:
  id: fb466c23-7c4e-4880-9b01-799bbe661819
  slug: circleci/6DTWpyeyBHdGJ5Mne3i1gj/Y2ewQnBwaQkXpcc6apT1fW
  name: Inkleaf
